# Generated by Django 5.2.4 on 2025-12-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noti_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='noti_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='noti_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='noti_follows',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='noti_likes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='noti_weekly',
            field=models.BooleanField(default=True),
        ),
    ]
