# Generated by Django 5.2.4 on 2025-12-22 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_noti_comments_user_noti_daily_user_noti_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='noti_email',
        ),
    ]
