# Generated by Django 5.2.4 on 2025-12-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_noti_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('email', '이메일'), ('google', '구글'), ('naver', '네이버'), ('kakao', '카카오')], default='email', max_length=20, verbose_name='가입 경로'),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소셜로그인 ID'),
        ),
    ]
