# Generated by Django 5.2.4 on 2025-12-22 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_provider_user_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='사용자 이름은 영문, 숫자, 밑줄(_)만 포함할 수 있습니다.', regex='^[a-zA-Z0-9_]+$')], verbose_name='사용자 이름'),
        ),
    ]
