# Generated by Django 5.2.4 on 2025-12-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_access_token',
            field=models.TextField(blank=True, null=True, verbose_name='소셜 액세스 토큰'),
        ),
    ]
