# Generated by Django 5.2.4 on 2025-12-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_social_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
