# Generated by Django 5.2.4 on 2025-12-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', '좋아요'), ('comment', '댓글'), ('follow', '팔로우'), ('daily', '데일리 질문'), ('weekly', '위클리 베스트')], max_length=20),
        ),
    ]
