# Generated by Django 5.2.4 on 2025-12-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='total_dwell_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dwelltime',
            name='dwell_seconds',
            field=models.FloatField(),
        ),
    ]
