# Generated by Django 5.2.9 on 2025-12-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_created_at_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='music_artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='music_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
