# Generated by Django 5.2.4 on 2025-12-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_music_artist_article_music_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
