# Generated by Django 5.2.4 on 2025-12-22 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_youtube_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='youtube_id',
        ),
    ]
