# Generated by Django 5.2.4 on 2025-12-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('culture', '시사/문화'), ('reflection', '자기성찰'), ('daily', '일상 기록'), ('creative', '창의적')], max_length=20)),
                ('release_date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['-release_date'],
            },
        ),
    ]
