# Generated by Django 5.2.4 on 2025-12-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_rec_artist_question_rec_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rec_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
